local RemoteNames = {}

RemoteNames.RemotesFolder = "Remotes"

RemoteNames.UpdateState = "UpdateState"
RemoteNames.UpdateTimer = "UpdateTimer"
RemoteNames.Announce = "Announce"
RemoteNames.MatchResult = "MatchResult"
RemoteNames.RoundEvent = "RoundEvent"

RemoteNames.SpectatorAction = "SpectatorAction"

RemoteNames.ShopRequest = "ShopRequest"
RemoteNames.ShopUpdate = "ShopUpdate"

RemoteNames.BE_AddCoins = "BE_AddCoins"

RemoteNames.MissionsUpdate = "MissionsUpdate"
RemoteNames.MissionsClaim = "MissionsClaim"
RemoteNames.MissionsRequest = "MissionsRequest"

RemoteNames.CrateOpenRequest = "CrateOpenRequest"
RemoteNames.CrateOpenResult = "CrateOpenResult"
RemoteNames.CrateDataRequest = "CrateDataRequest"
RemoteNames.CrateDataUpdate = "CrateDataUpdate"

-- INVENTORY
RemoteNames.InventoryRequest = "InventoryRequest"
RemoteNames.InventoryUpdate = "InventoryUpdate"
RemoteNames.InventoryEquip = "InventoryEquip"

RemoteNames.PremiumRequest = "PremiumRequest"
RemoteNames.PremiumUpdate = "PremiumUpdate"

RemoteNames.PetsRequest = "PetsRequest"
RemoteNames.PetsUpdate = "PetsUpdate"
RemoteNames.PetsEquip = "PetsEquip"

RemoteNames.BattlePassRequest = "BattlePassRequest"
RemoteNames.BattlePassUpdate = "BattlePassUpdate"
RemoteNames.BattlePassClaim = "BattlePassClaim"

RemoteNames.SkillsRequest = "SkillsRequest"
RemoteNames.SkillsUpdate = "SkillsUpdate"
RemoteNames.SkillsEquip = "SkillsEquip"
RemoteNames.SkillsUse = "SkillsUse"

RemoteNames.LeaderboardUpdate = "LeaderboardUpdate"
RemoteNames.AudienceVoteUpdate = "AudienceVoteUpdate"

return RemoteNames
