local RemoteNames = {}

RemoteNames.RemotesFolder = "Remotes"

RemoteNames.UpdateState = "UpdateState"
RemoteNames.UpdateTimer = "UpdateTimer"
RemoteNames.Announce = "Announce"
RemoteNames.MatchResult = "MatchResult"
RemoteNames.RoundEvent = "RoundEvent"

RemoteNames.SpectatorAction = "SpectatorAction"

RemoteNames.ShopRequest = "ShopRequest"
RemoteNames.ShopUpdate = "ShopUpdate"

RemoteNames.BE_AddCoins = "BE_AddCoins"

RemoteNames.MissionsUpdate = "MissionsUpdate"
RemoteNames.MissionsClaim = "MissionsClaim"
RemoteNames.MissionsRequest = "MissionsRequest"

RemoteNames.CrateOpenRequest = "CrateOpenRequest"
RemoteNames.CrateOpenResult = "CrateOpenResult"
RemoteNames.CrateDataRequest = "CrateDataRequest"
RemoteNames.CrateDataUpdate = "CrateDataUpdate"

-- INVENTORY
RemoteNames.InventoryRequest = "InventoryRequest"
RemoteNames.InventoryUpdate = "InventoryUpdate"
RemoteNames.InventoryEquip = "InventoryEquip"

return RemoteNames
